---
- name: change user shell to bash
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash

- name: Install soft
  apt:
    name: "{{ item }}"
    state: present 
    update_cache: yes 
    install_recommends: yes
  environment:
    - NEEDRESTART_MODE: automatically
  with_items:
  - net-tools
  - unzip
  - python3.10-venv
  - python3-pip
  tags: pre-install
